apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-frontend
spec:
  workspaces:
    - name: workspace-frontend-tenant 
  stepTemplate:
    env:
      - name: API_KEY
        valueFrom:
          secretKeyRef:
            name: $(params.continuous-delivery-context-secret)
            key: $(params.ibmcloud-apikey-secret-key)
            optional: true
      - name: TRIGGER_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.annotations['devops.cloud.ibm.com/trigger-name']
  params:
    - name: ibmcloud-api
      description: the ibmcloud api
    - name: continuous-delivery-context-secret
      description: name of the secret containing the continuous delivery pipeline context secrets
      default: secure-properties
    - name: ibmcloud-apikey-secret-key
      description: field in the secret that contains the api key used to login to ibmcloud
      default: apikey
    - name: IBM_CLOUD_RESOURCE_GROUP
    - name: IBM_CLOUD_REGION
    - name: CODE_ENGINE_PROJECT_NAME
    - name: APPID_SERVICE_KEY_NAME
    - name: POSTGRES_SERVICE_KEY_NAME
    - name: REGISTRY_URL
    - name: REGISTRY_NAMESPACE
    - name: REGISTRY_TAG
    - name: REGISTRY_SECRET_NAME
    - name: IMAGES_NAME_FRONTEND
    - name: APPLICATION_CONTAINER_NAME_FRONTEND
    - name: APPLICATION_CONTAINER_NAME_BACKEND
    - name: APPLICATION_CATEGORY
  steps:
    - name: deploy-frontend
      image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.3
      script: |
        #!/bin/bash
        echo "deploy-frontend"        
        set -x
        cd $(workspaces.workspace-frontend-tenant.path)

        ibmcloud config --check-version false
        ibmcloud login -a $(params.ibmcloud-api) --no-region --apikey $API_KEY
        ibmcloud target -g $(params.IBM_CLOUD_RESOURCE_GROUP)
        ibmcloud target -r $(params.IBM_CLOUD_REGION)

        ibmcloud plugin install code-engine  
        
        #####################

        ibmcloud ce project select -n $(params.CODE_ENGINE_PROJECT_NAME)
        ibmcloud ce project select -n $(params.CODE_ENGINE_PROJECT_NAME) --kubecfg
        ibmcloud ce project get --name $(params.CODE_ENGINE_PROJECT_NAME)

        #####################

        ibmcloud resource service-key $(params.APPID_SERVICE_KEY_NAME) --output JSON > ./appid-key-temp.json

        APPID_CLIENT_ID=$(cat ./appid-key-temp.json | jq '.[].credentials.clientId' | sed 's/"//g' )
        APPID_APPLICATION_DISCOVERYENDPOINT=$(echo $result | sed -n 's|.*"discoveryEndpoint":"\([^"]*\)".*|\1|p')

        #####################
   
        ibmcloud ce secret create --name appid.client-id-fronted  --from-literal "VUE_APPID_CLIENT_ID=$APPID_CLIENT_ID"
        ibmcloud ce secret create --name appid.discovery-endpoint --from-literal "VUE_APPID_DISCOVERYENDPOINT=$APPID_APPLICATION_DISCOVERYENDPOINT"

        #####################

        ACTION="create"
        CHECK=$(ibmcloud ce application get --name $(params.APPLICATION_CONTAINER_NAME_FRONTEND) | awk '/Name:/ {print $2}')
        if [[ $CHECK == $(params.APPLICATION_CONTAINER_NAME_FRONTEND)* ]]
        then
            echo "Application already exists"
            ACTION="update"
        else
            echo "Application does not exist"
        fi

        IMAGE_NAME_FRONTEND="$(params.REGISTRY_URL)"/"$(params.REGISTRY_NAMESPACE)"/"$(params.IMAGES_NAME_FRONTEND)":"$(params.REGISTRY_TAG)"
        echo $IMAGE_NAME_FRONTEND
        SERVICE_CATALOG_URL=$(ibmcloud ce application get --name "$(params.APPLICATION_CONTAINER_NAME_BACKEND)" -o url)
        ibmcloud ce application $ACTION --name $(params.APPLICATION_CONTAINER_NAME_FRONTEND) \
                                   --image $IMAGE_NAME_FRONTEND \
                                   --cpu "1" \
                                   --memory "2G" \
                                   --env-from-secret appid.client-id-fronted \
                                   --env-from-secret appid.discovery-endpoint \
                                   --env VUE_APP_API_URL_PRODUCTS="$SERVICE_CATALOG_URL/base/category" \
                                   --env VUE_APP_API_URL_ORDERS="$SERVICE_CATALOG_URL/base/customer/Orders" \
                                   --env VUE_APP_API_URL_CATEGORIES="$SERVICE_CATALOG_URL/base/category" \
                                   --env VUE_APP_CATEGORY_NAME="$(params.APPLICATION_CATEGORY)" \
                                   --env VUE_APP_HEADLINE="$(params.APPLICATION_CONTAINER_NAME_FRONTEND)" \
                                   --env VUE_APP_ROOT="/" \
                                   --registry-secret "$(params.REGISTRY_SECRET_NAME)" \
                                   --max-scale 1 \
                                   --min-scale 1 \
                                   --port 8080 

        SERVICE_FRONTEND_URL=$(ibmcloud ce application get --name "$(params.APPLICATION_CONTAINER_NAME_FRONTEND)" -o url)
        echo "SERVICE_FRONTEND_URL: $SERVICE_FRONTEND_URL"
        ibmcloud ce application events --application $(params.APPLICATION_CONTAINER_NAME_FRONTEND)
